name: Validate Features

on:
    workflow_call: # Reusable workflow parts (callee) to be called by other workflows
        inputs:
            dicts_changed:
                type: string
                description: 'Modification status on Keydo dictionaries (dicts/*)'
                required: false
                default: 'true'
            logic_changed:
                type: string
                description: 'Modification status on Keydo logic (logic/*)'
                required: false
                default: 'true'

jobs:
    logic:
        runs-on: ubuntu-latest
        if: ${{ inputs.logic_changed == 'true' }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Syntax and linting check for Lua
              run: |
                  # Check for syntax and linting issues in Lua files
                  bash scripts/validate-logic.sh --install-deps
