name: Validate Commits

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    detect-changes:
        runs-on: ubuntu-latest
        outputs:
            dicts_changed: ${{ steps.filter-changes.outputs.dicts }}
            logic_changed: ${{ steps.filter-changes.outputs.logic }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Filter changes
              uses: dorny/paths-filter@v4
              id: filter-changes
              with:
                  filters: |
                      logic:
                          - 'logic/**'
                      dicts:
                          - 'dicts/**'

    validate:
        needs: detect-changes
        uses: ./.github/workflows/_validate-features.yaml
        with:
            dicts_changed: ${{ needs.detect-changes.outputs.dicts_changed }}
            logic_changed: ${{ needs.detect-changes.outputs.logic_changed }}
