name: Validate Commits

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    detect-changes:
        runs-on: ubuntu-latest
        outputs:
            dicts_changed: ${{ steps.filter-changes.outputs.dicts }}
            logic_changed: ${{ steps.filter-changes.outputs.logic }}
            schema_changed: ${{ steps.filter-changes.outputs.schema }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Filter changes
              uses: dorny/paths-filter@v4
              id: filter-changes
              with:
                  filters: |
                      dicts:
                          - 'dicts/**'
                      logic:
                          - 'logic/**'
                      schema:
                          - 'rime/**'
                          - 'schema/**'

    pre-validate:
        needs: detect-changes
        uses: ./.github/workflows/_validate-features.yaml
        with:
            dicts_changed: ${{ needs.detect-changes.outputs.dicts_changed }}
            logic_changed: ${{ needs.detect-changes.outputs.logic_changed }}

    build:
        needs: detect-changes
        if: >-
            ${{
                needs.detect-changes.outputs.dicts_changed == 'true' ||
                needs.detect-changes.outputs.logic_changed == 'true' ||
                needs.detect-changes.outputs.schema_changed == 'true'
            }}
        uses: ./.github/workflows/_build-images.yaml

    post-validate:
        needs: [detect-changes, build]
        uses: ./.github/workflows/_validate-schema.yaml
        with:
            dicts_changed: ${{ needs.detect-changes.outputs.dicts_changed }}
            logic_changed: ${{ needs.detect-changes.outputs.logic_changed }}
            schema_changed: ${{ needs.detect-changes.outputs.schema_changed }}
