name: Validate Features

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    detect-changes:
        runs-on: ubuntu-latest
        outputs:
            logic_changed: ${{ steps.filter-changes.outputs.logic }}
            dicts_changed: ${{ steps.filter-changes.outputs.dicts }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Filter changes
              uses: dorny/paths-filter@v4
              id: filter-changes
              with:
                  filters: |
                      logic:
                          - 'logic/**'
                      dicts:
                          - 'dicts/**'

    validate-logic:
        runs-on: ubuntu-latest
        needs: detect-changes
        if: ${{ needs.detect-changes.outputs.logic_changed == 'true' }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Syntax and linting check for Lua
              run: |
                  # Check for syntax and linting issues in Lua files
                  bash scripts/validate-logic.sh --install-deps
